version: '3'

services:
  web:
    container_name: web
    hostname: web
    image: nginx:${NGINX_VERSION:-alpine}
    depends_on:
      - app
    ports:
            - "${PORT:-8443}:443"
    volumes:
      - ./docker/web/conf.d:/etc/nginx/conf.d
      - ./docker/web/ssl:/etc/nginx/ssl
      - ./log/nginx:/var/log/nginx
    networks:
      - nginx_network

  app:
    container_name: app
    hostname: app
    image: ${using_image:-app_fastapi_py38:latest}
    expose:
      - 8000
    networks:
      - nginx_network
      - db_network
    volumes:
      - ./app:/app/app
    # command: ${app_command:-"run reload"}
    command: "run reload_proxy"
    # depends_on:
    #   - db_postgis
    # links:
    #   - db_postgis:db_postgis

networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge
